[font]
size = 12


[font.normal]
family = "CaskaydiaCove Nerd Font"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0

[env]
TERM = "xterm-256color"


[colors]

draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282727"

[colors.normal]
black = "#282727"
red = "#cb231d"
green = "#98961a"
yellow = "#d69821"
blue = "#458487"
magenta = "#b06185"
cyan = "#689c69"
white = "#a89883"

[colors.bright]
black = "#928273"
red = "#fa4834"
green = "#b8ba26"
yellow = "#f9bc2f"
blue = "#83a497"
magenta = "#d2859a"
cyan = "#8ebf7b"
white = "#ebdab1"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Alt"
