#!/usr/bin/env bash

function mac_setup() {
  echo "Setting up Mac"
  # Install xcode command line tools
  xcode-select --install
}

function ubuntu_setup() {
  echo "Setting up Ubuntu"
  sudo apt update && sudo apt upgrade -y
  sudo apt install -y git
}

# Check whether we are on a Mac or Linux

if [ "$(uname)" == "Darwin" ]; then
  ID="mac"
elif [ -f "/etc/lsb-release" ]; then
  ID="ubuntu"
else
  ID="unsupported"
fi

case $ID in
  ubuntu)
    ubuntu_setup
    ;;
  mac)
    mac_setup
    ;;
  *)
    echo $ID
    _task "Unsupported OS"
    _cmd "echo 'Unsupported OS'"
    ;;
esac

mkdir -p ~/.config/dotfiles
git clone https://github.com/landerwells/dotfiles.git ~/.config/dotfiles
# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Make sure everything is up to date and installed
# sudo apt update && sudo apt upgrade -y



# # Specify the source directory and destination directory
# DOTFILES_REPO="$HOME/.config/dotfiles"
# CONFIG_DIR="$HOME/.config"

# # # Function to create symbolic link if the destination doesn't exist
# # create_symlink() {
#   source_dir="$1"
#   destination_dir="$2"

#     # Check if the destination directory already exists
#     if [ -e "$destination_dir" ]; then
#       echo "The destination directory $destination_dir already exists."
#     else
#       # Create symbolic link
#       ln -s "$source_dir" "$destination_dir"
#       echo "Created symbolic link for $source_dir to $destination_dir"
#     fi
#   }

# # Create symbolic links for specific directories
# create_symlink "$DOTFILES_REPO/nvim" "$CONFIG_DIR/nvim"
# create_symlink "$DOTFILES_REPO/bash" "$CONFIG_DIR/bash"
# create_symlink "$DOTFILES_REPO/zsh" "$CONFIG_DIR/zsh"
# create_symlink "$DOTFILES_REPO/aliases" "$CONFIG_DIR/aliases"
# create_symlink "$DOTFILES_REPO/tmux" "$CONFIG_DIR/tmux"
# create_symlink "$DOTFILES_REPO/git" "$CONFIG_DIR/git"
# create_symlink "$DOTFILES_REPO/starship.toml" "$CONFIG_DIR/starship.toml"
# create_symlink "$DOTFILES_REPO/alacritty" "$CONFIG_DIR/alacritty"

# # Create symbolic links for mac specific directories
# if [ "$(uname)" == "Darwin" ]; then
#   create_symlink "$DOTFILES_REPO/yabai" "$CONFIG_DIR/yabai"
#   create_symlink "$DOTFILES_REPO/skhd" "$CONFIG_DIR/skhd"
#   create_symlink "$DOTFILES_REPO/karabiner" "$CONFIG_DIR/karabiner"
#   create_symlink "$DOTFILES_REPO/linearmouse" "$CONFIG_DIR/linearmouse"
#   create_symlink "$DOTFILES_REPO/iterm2" "$CONFIG_DIR/iterm2"
# fi

# create_symlink "$DOTFILES_REPO/haskeline" "$HOME/.haskeline"
# create_symlink "$DOTFILES_REPO/.profile" "$HOME/.profile"
# create_symlink "$DOTFILES_REPO/.zprofile" "$HOME/.zprofile"


