#!/usr/bin/env bash

brew install neovim
brew install tmux
brew install starship
brew install ripgrep
brew install node
brew install fzf
brew install eza
brew install font-caskaydia-cove-nerd-font
brew install "font-inconsolata-nerd-font"
brew install "font-jetbrains-mono-nerd-font"
