I would like to create a script that I can run from anywhere that will rebuild
my system if needed. First I need to transition away from ~apps/~ directory and
put everything in bin, and then keep that more organized with scripts.




Some goals I have for this rewrite:
- Fully declarative Syncthing with secrets managed in repo
- Password management in repo
- Home-manager configuration that will allow my dotfiles to be set up on any
  machine
  
  

One configuration to be installed on any system that isn't regular nix,
supporting x86 linux, and aarch macs, in addition to the configuration that will
get installed NixOS machines



* Personal Configuration
I would like to use home-manager for all of the configuration that will be
common across any machine. I would like it to have my minimal   



* Read-later and RSS feed
Needs to be able to support firefox on mac, and safari on ios. I would love if
it could download stuff, and perhaps if I could self host it as well that would
be cool






* SSH configuration
Manage SSH keys and everything stays real nice

