github.com:
    git_protocol: ssh
    users:
        landerwells:
            oauth_token: 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
    user: landerwells
    oauth_token: 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
