# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = '''
$os$username$hostname$kubernetes$directory(238)$git_branch$git_status
$character(238)
'''

# Drop ugly default prompt characters
[character]
success_symbol = '[λ](bold 61) '
error_symbol = '[❯](bold 124) '

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = ' 󰣇'
Ubuntu = ' '
Macos = ' 󰀵'

# Shows the username
[username]
style_user = '166 bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
style = 'bold 136'
format = '@(bold 15)[$hostname]($style) '
disabled = false

# Shows current directory
[directory]
style = '64 bold'
truncation_length = 100
truncate_to_repo = false
home_symbol = "~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

# Shows current git branch
[git_branch]
symbol = ' '
format = 'on [$symbol$branch]($style) '
style = 'bold 33'

# Shows current git status
[git_status]
style = '61'

[docker_context]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
