[settings]
default_action = "block"         # or "allow"
log_violations = true
notify_on_block = true
strict_mode = false              # optional: if true, disables temporary overrides

[[blocks]]
name = "Algorithmic Feeds"
active_by_default = true
whitelist = [
  "instagram.com/direct/inbox",
  "instagram.com/p/*",
  "linkedin.com/in/*",
  "reddit.com/message/inbox",
  "reddit.com/r/*",
  "reddit.com/search*",
  "reddit.com/user/*",
  "twitter.com/i/timeline",
  "youtube.com/@*",
  "youtube.com/c/*",
  "youtube.com/channel/*",
  "youtube.com/feed/library/*",
  "youtube.com/feed/subscriptions",
  "youtube.com/playlist?list=*",
  "youtube.com/results?search_query=*",
  "youtube.com/user/*",
  "youtube.com/watch?*"
]
blacklist = [
  "facebook.com",
  "instagram.com",
  "linkedin.com",
  "reddit.com",
  "tiktok.com",
  "twitter.com/home",
  "youtube.com",
]

[[blocks]]
name = "Stocks"
active_by_default = false
blacklist = [
  "robinhood.com",
  "tradingview.com",
  "finance.yahoo.com"
]

[[blocks]]
name = "Internet"
active_by_default = true
blacklist = [
  "amazon.com",
  "google.com",
]

[[schedule]]
block = "algorithmic_feeds"
days = ["Mon", "Tue", "Wed", "Thu", "Fri"]
start = "08:00"
end = "18:00"

[[schedule]]
block = "stock_sites"
days = ["Mon", "Fri"]
start = "09:30"
end = "16:00"
