export LESSHISTFILE=""
export MANPAGER='nvim +Man!'
export VISUAL=nvim
export EDITOR=nvim
export XCURSOR_PATH="$HOME/dotfiles/cursors"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
