-- /home/landerwells/dotfiles/wallpapers/output.sdr/metadata.gif.lua
return {
    ["annotations"] = {},
    ["bbox"] = {},
    ["doc_pages"] = 72,
    ["doc_path"] = "/home/landerwells/dotfiles/wallpapers/output.gif",
    ["doc_props"] = {},
    ["flipping_scroll_mode"] = false,
    ["flipping_zoom_mode"] = "page",
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["inverse_reading_order"] = false,
    ["last_page"] = 72,
    ["page_overlap_style"] = "dim",
    ["page_positions"] = {},
    ["panel_zoom_enabled"] = false,
    ["partial_md5_checksum"] = "228a1d127270c455241643c5d5c0f42e",
    ["percent_finished"] = 1,
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["summary"] = {
        ["modified"] = "2025-10-22",
        ["status"] = "reading",
    },
    ["toc_ticks_ignored_levels"] = {},
    ["zoom_mode"] = "contentwidth",
}
