{
  pkgs,
  inputs,
}:
with pkgs; let
  shared-packages = import ../shared/packages.nix {inherit pkgs inputs;};
in
  shared-packages
  ++ [
    # Desktop applications (that can't be shared easily with MacOS)
    anki
    blender
    blueman
    discord
    firefox
    flatpak
    font-manager
    fontconfig
    gcc
    ghostty
    gnuplot
    hyprlock
    hyprpaper
    hyprpicker
    hyprshot
    libvterm
    mangohud
    obs-studio
    obsidian
    pamixer
    pavucontrol
    perf
    racket-minimal
    rofi
    sioyek
    spotify
    unixtools.ifconfig
    unixtools.netstat
    valgrind
    vlc
    vscode
    waybar
    wiremix
    wireplumber
    wl-clipboard
    xwayland
    xeyes
    xprop
    zathura
    zed-editor
    zotero
  ]
